//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamesDays.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NamesDay
    {
        public NamesDay()
        {
            this.Names = new HashSet<Name>();
        }
    
        public int NameDayId { get; set; }
        public System.DateTime NameDayDate { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Name> Names { get; set; }
    }
}
